name: AI Naming Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    name: Review Naming Conventions
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run AI naming review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BLACKBOX_API_KEY: ${{ secrets.BLACKBOX_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          LLM_MODEL: ${{ vars.LLM_MODEL || 'gpt-4o-mini' }}
          MAX_TOKENS: ${{ vars.MAX_TOKENS || '1000' }}
          LLM_TEMPERATURE: ${{ vars.LLM_TEMPERATURE || '0.3' }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL || 'INFO' }}
        run: npm run review

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: review-logs
          path: |
            *.log
          retention-days: 7
