# Example workflow for using AI Naming Reviewer in autofix mode
# Copy this to your repository's .github/workflows/ directory

name: AI Naming Autofix

on:
  pull_request:
    types: [labeled, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    # Only run on same-repo PRs with the auto-naming-fix label
    if: |
      github.event.pull_request.head.repo.full_name == github.repository &&
      contains(github.event.pull_request.labels.*.name, 'auto-naming-fix')
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: AI Naming Autofix
        id: autofix
        uses: yourusername/ai-naming-reviewer@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          mode: autofix
          # Optional: customize settings
          # llm-model: gpt-4o-mini
          # max-tokens: 1000
          # temperature: 0.3
          # log-level: INFO
          # autofix-label: auto-naming-fix
      
      - name: Report Results
        if: always()
        run: |
          echo "✅ AI Naming Autofix completed"
          echo "📊 Suggestions: ${{ steps.autofix.outputs.suggestions-count }}"
          echo "🔧 Auto-fixes applied: ${{ steps.autofix.outputs.autofixes-applied }}"
          echo "💰 Estimated cost: \$${{ steps.autofix.outputs.estimated-cost }}"
